settings:
  title: 'Hammer-Tech Status Page'
  url: 'https://status.hammer-tech.net' # used for Slack messages
  logo: H-T_logo-l.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Home-stat # unique identifier
    name: Home
    description: 'Hammer-Tech landing page.' # default=empty
    url: 'https://Home.hammer-tech.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: OMBI-stat
    name: OMBI
    description: 'Plex component'
    url: 'https://www.hammer-tech.net'
    method: GET
    expectStatus: 200
  
  - id: Sonarr-stat
    name: Sonarr
    description: 'Plex component'
    url: 'https://sonarr.hammer-tech.net'
    method: GET
    expectStatus: 200
    
  - id: Radarr-stat
    name: Radarr
    description: 'Plex component'
    url: 'https://radarr.hammer-tech.net'
    method: GET
    expectStatus: 200
