settings:
  title: 'Hammer-Tech Status Page'
  url: 'https://status.hammer-tech.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Home # unique identifier
    name: Home.hammer-tech.net
    description: 'Hammer-Tech landing page.' # default=empty
    url: 'https://Home.hammer-tech.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: OMBI
    name: www.hammer-tech.net
    description: 'Plex'
    url: 'https://www.hammer-tech.net'
    method: GET
    expectStatus: 200
